# Generated by Django 4.0.4 on 2023-04-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=10)),
                ('phone', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=30, null=True)),
                ('pincode', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('address', models.TextField(blank=True, default=None, max_length=200, null=True)),
                ('pic', models.FileField(blank=True, default=None, null=True, upload_to='image')),
            ],
        ),
    ]
