# Generated by Django 4.0.4 on 2023-04-13 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_contact_newslatter'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fund_title', models.CharField(max_length=500)),
                ('fund_description', models.TimeField()),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Done')], default=1)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.state')),
            ],
        ),
    ]
