# Generated by Django 4.0.4 on 2023-04-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_state_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
