# Generated by Django 4.0.4 on 2023-04-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_fund_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='fund_description',
            field=models.TextField(),
        ),
    ]
