# Generated by Django 4.0.4 on 2023-04-13 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_fund_fund_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainApp.userdetail'),
        ),
    ]
