# Generated by Django 4.0.4 on 2023-04-13 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_fund_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.userdetail'),
        ),
    ]
