# Generated by Django 4.0.4 on 2023-04-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_alter_fund_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='pic',
            field=models.FileField(blank=True, default=None, null=True, upload_to='image'),
        ),
    ]
