# Generated by Django 4.0.4 on 2023-04-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_fund_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='pic',
            field=models.FileField(blank=True, default=None, null=True, upload_to='meadia/image'),
        ),
    ]
