# Generated by Django 4.0.4 on 2023-04-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_alter_fund_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='pic',
            field=models.FileField(blank=True, default=None, null=True, upload_to='image'),
        ),
    ]
